#!/usr/bin/env bash
#
# © 2018-2019 Konstantin Gredeskoul, All Rights Reserved.
# MIT License
#
# WARNING: This BASH script is completely optional. You don't need it to build this project.
#
# If you choose to run this script to build the project, run:
#
#     $ ./build-and-run
#
# It will clean, build and run the tests.
#

[[ -z $(which git) ]] && {
  echo "You need git installed. Please run 'xcode-select --install' first."
  exit 1
}

export BashMatic="${HOME}/.bashmatic"

[[ -s ${BashMatic}/init.sh ]] || {
  rm -rf "${BashMatic}" 2>/dev/null
  git clone https://github.com/kigster/bashmatic "${BashMatic}" 2>&1 1>/dev/null
}

source "${BashMatic}/init.sh"

export ProjectRoot=$(pwd)
export BuildDir="${ProjectRoot}/build/run"
export BashLibRoot="${ProjectRoot}/bin/lib-bash"
export LibBashRepo="https://github.com/kigster/lib-bash"

brainfuck.setup() {
  hl.subtle "Creating Build Folder..."
  run "mkdir -p build/run"
  run "git submodule init && git submodule update"
}

brainfuck.clean() {
  hl.subtle "Cleaning output folders..."
  run 'rm -rf bin/d* include/d* lib/*'
}

brainfuck.build() {
  run "cd build/run"
  run "cmake ../.. "
  run.set-next show-output-on
  run "make -j 12"
  run "make install | egrep -v 'gmock|gtest'"
  run "cd ${ProjectRoot}"
}

brainfuck.tests() {
  if [[ -f bin/brainfuck_tests ]]; then
    run.set-next show-output-on
    run "echo && bin/brainfuck_tests"
  else
    printf "${bldred}Can't find installed executable ${bldylw}bin/brainfuck_tests.${clr}\n"
    exit 2
  fi
}

main() {
  brainfuck.setup
  brainfuck.build
  brainfuck.tests
}

(( $_s_ )) || main
